src/SysuLesson/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import settings

urlpatterns = [
    url(r'', include('base.urls', namespace='base')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^exchange/', include('exchange.urls', namespace='exchange')),
    url(r'^grade/', include('grade.urls', namespace='grade')),
    url(r'^lesson/', include('lesson.urls', namespace='lesson')),
    url(r'^meterial/', include('meterial.urls', namespace='meterial')),
    url(r'^school/', include('school.urls', namespace='school')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }, name='media'),
]

src/base/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^test/$', views.test, name='test'),
]

src/exchange/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.all_exchanges, name='all_exchanges'),
    url(r'^home/$', views.my_exchanges, name='my_exchanges'),
    url(r'^form/$', views.new_exchange, name='new_exchange'),
    url(r'^create/$', views.create_exchange, name='create_exchange'),
    url(r'^(?P<exchange_id>[0-9]+)/finish/$', views.finish_exchange, name='finish_exchange'),
    url(r'^(?P<exchange_id>[0-9]+)/cancel/$', views.cancel_exchange, name='cancel_exchange'),
    url(r'^(?P<exchange_id>[0-9]+)/$', views.exchange_detail, name='exchange_detail'),
]

src/exchange/models.py
# -*- coding: utf-8 -*-
from django.db import models

from django.contrib.auth.models import User
from lesson.models import Lesson

# Create your models here.

class Exchange(models.Model):
    user = models.ForeignKey(User)
    lessonIn = models.CharField(max_length=128, blank=True, null=True)
    lessonOut = models.CharField(max_length=128)
    phone = models.CharField(max_length = 16)
    email = models.EmailField(max_length = 64)
    description = models.TextField(null = True, blank = True)
    deadline = models.DateTimeField(null = True, blank = True)
    time = models.DateTimeField(auto_now_add=True)
    finished = models.BooleanField(default=False)

    def finish(self):
        self.finished = True

    def get_state(self):
        if self.finished:
            return '已完成'
        else:
            return '进行中'

    def __unicode__(self):
        try:
            return 'Exchange hold by ' + self.user + \
                ' for lesson ' + str(self.lesson.id)
        except:
            return 'An Exchange'

    class Meta:
        ordering = ['-time']
        verbose_name = 'Exchange'
        verbose_name = 'Exchanges'

src/exchange/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from django.utils import timezone
import datetime

from .models import Exchange
from lesson.models import Lesson
from api.sysu import Sysuer
from api.parser import parseResultOfCourseSelection, parseScore

@login_required
@require_GET
def all_exchanges(request):
    """ interface URL: /exchange/ """
    exchanges = Exchange.objects.all()
    paginator = Paginator(exchanges, 5)
    page = request.GET.get('page')
    try:
        exchanges_per_page = paginator.page(page)
    except PageNotAnInteger:
        exchanges_per_page = paginator.page(1)
    except EmptyPage:
        exchanges_per_page = paginator.page(paginator.num_pages)
    current_page = exchanges_per_page.number
    pages_num = paginator.num_pages
    pages = [current_page + i for i in xrange(-6, 10) if current_page + i > 0 and current_page + i <= pages_num]
    return render(request, 'exchange/all_exchanges.html',{
        'exchanges':exchanges_per_page,
        'pages':pages[:10]})

@login_required
@require_GET
def my_exchanges(request):
    """ interface URL: /exchange/home/ """
    user = request.user
    exchanges = user.exchange_set.all()
    return render(request, 'exchange/my_exchanges.html',{
        'exchanges':exchanges})

@login_required
@require_GET
def new_exchange(request):
    """ interface URL: /exchange/form/ """
    user = Sysuer(username=request.user.username,
        cookie=request.session['cookie'])
    data = parseResultOfCourseSelection(user)
    lessons = [lesson for lesson in data if lesson['xnd'] == '2014-2015' and lesson['xq'] == '3' and int(lesson['kclbm'])>20]
    return render(request, 'exchange/new_exchange.html', {
        'lessons': lessons,
        })

@login_required
@require_POST
def create_exchange(request):
    """ interface URL: /exchange/create/ """
    lessonOut = request.POST['lessonOut']
    user = request.user
    lessonIn = request.POST['lessonIn']
    phone = request.POST['phone']
    email = request.POST['email']
    time = timezone.now()
    deadlineList = request.POST['deadline'].split('-')
    deadline = datetime.datetime(int(deadlineList[0]),
            int(deadlineList[1]), int(deadlineList[2]))
    exchange = Exchange(
            user = user,
            lessonOut = lessonOut,
            lessonIn = lessonIn,
            phone = phone,
            email = email,
            description = '',
            time = time,
            deadline = deadline,
    )
    exchange.save()
    return HttpResponseRedirect(reverse('exchange:all_exchanges'))

@login_required
@require_POST
def finish_exchange(request, exchange_id):
    """ interface URL: /exchange/id/finish"""
    exchange = get_object_or_404(Exchange, pk=exchange_id)
    exchange.finish()
    exchange.save()
    return HttpResponseRedirect(reverse('exchange:exchange_detail', args=(exchange.id, )))

@login_required
@require_POST
def cancel_exchange(request, exchange_id):
    exchange = get_object_or_404(Exchange, pk=exchange_id)
    exchange.delete()
    return HttpResponseRedirect(reverse('exchange:my_exchanges'))

@login_required
@require_GET
def exchange_detail(request, exchange_id):
    exchange = get_object_or_404(Exchange, pk=exchange_id)
    not_finished = not exchange.finished
    current_user = request.user == exchange.user
    display = not_finished and current_user
    print not_finished, current_user
    return render(request, 'exchange/exchange_detail.html',{
        'exchange': exchange,
        'display': display})
# Create your views here.

src/exchange/templates/exchange/all_exchanges.html
{% extends 'base/base.html' %}

{% block import %}
{% load staticfiles %}
<link href="{% static 'exchange/css/all_exchanges.css' %}" rel="stylesheet" type="text/css">
{% endblock import %}

{% block main %}
<div class="container">
    <h2>浏览换课信息
        <a id="create" href="{% url 'exchange:new_exchange' %}" class="btn btn-success">发布换课信息</a>
    </h2>

    <div><!-- Exchange info list -->
        {% if exchanges %}
        {% for exchange in exchanges %}
            <a href="{% url 'exchange:exchange_detail' exchange.id %}">
                <div class="panel panel-primary">
                    <div class="panel-heading ">
                        <div class="h6 text-left">计划换出课程：{{ exchange.lessonOut }}
                            {% if exchange.lessonIn %}<br>希望得到的课程：{{ exchange.lessonIn }}{%endif%}</div>
                        <div class="text-right">{{ exchange.time|date:'Y-m-d' }} {{ exchange.time|date:'H:i' }}</div>
                    </div>
                    <div class="panel-body">
                        <div class="text-left">Phone:{{ exchange.phone }}<br>Email:{{ exchange.email }}</div>
                        <div class="text-right">{{ exchange.description }}</div>
                    </div>
                </div>
            </a>
        {% endfor %}
        {% else %}
        <p>还没人发布换课信息哦</p>
        {% endif %}
   </div>
    <!-- /.container -->

    <div class="container">
        <div class="pagination pagination-success">
            <ul>
                {% if exchanges.has_previous %}
                <li class="previous"><a href="?page={{ exchanges.previous_page_number }}" class="fui-arrow-left">前页</a></li>
                {% endif %}
                {% for page in pages %}
                <li {% if page == exchanges.number %}class="active"{% endif %}><a href="?page={{ page }}">{{ page }}</a></li>
                {% endfor %}
                {% if exchanges.has_next %}
                <li class="next"><a href="?page={{ exchanges.next_page_number }}" class="fui-arrow-right">后页</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock main %}

src/exchange/templates/exchange/exchange_detail.html
<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
<!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
{% extends 'base/base.html' %}

{% block main %}
<div class="container">
    <h2>换课信息详情
        <a id="create" href="{% url 'exchange:new_exchange' %}" class="btn btn-success">发布换课信息</a>
    </h2>
</div>
<!-- /.container -->

<div class="container well center-block">
    <div class="row">
        <dl class="dl-horizontal col-sm-6">
            <dt>计划换出的课程</dt>
            <dd >{{ exchange.lessonOut.title }}</dd>
        </dl>
        <dl class="dl-horizontal col-sm-6">
            <dt>计划得到的课程</dt>
            <dd>{{ exchange.lessonIn|default:'无' }}</dd>
        </dl>
        <dl class="dl-horizontal col-sm-6">
            <dt>电话</dt>
            <dd>{{ exchange.phone }}</dd>
        </dl>
        <dl class="dl-horizontal col-sm-6">
            <dt>Email</dt>
            <dd>{{ exchange.email }}</dd>
        </dl>
        <dl class="dl-horizontal col-sm-6">
            <dt>截止日期</dt>
            <dd>{{ exchange.deadline }}</dd>
        </dl>
        <dl class="dl-horizontal col-sm-6">
            <dt>发布日期</dt>
            <dd>{{ exchange.time }}</dd>
        </dl>
        {% if display %}
        <form action="{% url 'exchange:finish_exchange' exchange.id %}" method="post">
        {% csrf_token %}
        <div class="col-xs-6">
            <button type="submit" class="btn btn-success center-block">完成</button>
        </div>
        </form> 
        <form action="{% url 'exchange:cancel_exchange' exchange.id %}" method="post">
        {% csrf_token %}
        <div clss="col-xs-6">
            <button type="submit" class="btn btn-danger center-block">删除</button>
        </div>
        </form>
        {% endif %}
    </div>
</form>
{% endblock main %}

src/exchange/templates/exchange/my_exchanges.html
{% extends 'base/base.html' %}

{% block import %}
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'exchange/css/my_exchanges.css' %}">
{% endblock import %}

{% block main %}
<div class="panel panel-primary grade-panel">
    <div class="panel-heading">
        <span><span class="fui-document"></span> 我的换课信息
            <a class="btn btn-primary" href="{% url 'exchange:new_exchange' %}">发布换课信息</a>
        </span>
    </div>
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <th>用于交换的课程</th>
                    <th>希望得到的课程</th>
                    <th>交换状态</th>
                    <th>发布时间</th>
                </tr>
            </thead>
            <tbody>
            {% for exchange in exchanges %}
                <tr>
                    <td><a href="{% url 'exchange:exchange_detail' exchange.id %}">{{ exchange.lessonOut.title }}</a></td>
                    <td>{{ exchange.lessonIn.title|default:'我只是想送一门课' }}</td>
                    <td>{{ exchange.get_state_display }}</td>
                    <td>{{ exchange.time }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div>
{% endblock main %}

src/exchange/templates/exchange/new_exchange.html
<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
<!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
{% extends 'base/base.html' %}

{% block main %}
<div class="container">
    <h2>发布换课信息</h2>
</div>
<!-- /.container -->

<form class="container well" role="form" action="{% url 'exchange:create_exchange' %}" method="post">
{% csrf_token %}
    <div class="form-group">
        <div class="input-group">
            <label class="control-label input-group-addon" for="lessonIn">计划换出的课程</label>
            <select data-toggle="select" name="lessonOut" class="select select-primary select-block mbl form-control">
                {% for lesson in lessons %}
                <option value="{{ lesson.kcmc }}">{{ lesson.kcmc }}</option>
                {% empty %}
                <option value="">你没有可换出的课程=。=</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <label class="control-label input-group-addon" for="lessonOut">计划得到的课程</label>
            <input type="text" class="form-control" name="lessonIn" placeholder="请输入你希望得到的课程名称">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <label class="input-group-addon">电话</label>
            <input type="number" class="form-control" name="phone" placeholder="请输入您的电话号码。">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <label class="input-group-addon">Email</label>
            <input type="email" class="form-control" name="email" placeholder="请输入您的邮箱地址。">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <label class="input-group-addon">截止日期</label>
            <input type="date" class="form-control" name="deadline" placeholder="请输入信息的最后有效日期。"></input>
        </div>
    </div>
    <button type="submit" class="form-control">发布</button>
</form>
{% endblock main %}