src/SysuLesson/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import settings

urlpatterns = [
    url(r'', include('base.urls', namespace='base')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^exchange/', include('exchange.urls', namespace='exchange')),
    url(r'^grade/', include('grade.urls', namespace='grade')),
    url(r'^lesson/', include('lesson.urls', namespace='lesson')),
    url(r'^meterial/', include('meterial.urls', namespace='meterial')),
    url(r'^school/', include('school.urls', namespace='school')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }, name='media'),
]

src/base/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^test/$', views.test, name='test'),
]

src/exchange/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.all_exchanges, name='all_exchanges'),
    url(r'^home/$', views.my_exchanges, name='my_exchanges'),
    url(r'^form/$', views.new_exchange, name='new_exchange'),
    url(r'^create/$', views.create_exchange, name='create_exchange'),
    url(r'^(?P<exchange_id>[0-9]+)/finish/$', views.finish_exchange, name='finish_exchange'),
    url(r'^(?P<exchange_id>[0-9]+)/cancel/$', views.cancel_exchange, name='cancel_exchange'),
    url(r'^(?P<exchange_id>[0-9]+)/$', views.exchange_detail, name='exchange_detail'),
]

src/grade/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.get_personal_grade, name='grade'),
]

src/lesson/urls.py
from django.conf.urls import patterns, url


from lesson import views

urlpatterns = patterns('',
    url(r'^$', views.lessons_list, name='lessons_list'),
    url(r'^(?P<lesson_id>\d+)/$', views.lesson_detail, name='lesson_detail'),
    url(r'^home/$', views.select_result, name='select_result'),
)

src/base/models.py
from django.db import models

# Create your models here.

src/base/views.py
from django.shortcuts import render, redirect

from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from api.sysu import Sysuer
from api.parser import parseResultOfCourseSelection, parseScore
from api.getInfo import getGrades
import os

# Create your views here.

@login_required
@require_GET
def index(request):
    return render(request, 'base/index.html')

@login_required
def test(request):
    test = Sysuer(username=request.user.username,
        cookie=request.session['cookie'])
    data = parseResultOfCourseSelection(test)
    return render(request, 'base/test.html', {
        'data': data,
        })

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated():
        return redirect('/')

    nextPage = request.GET.get('next', '/')
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        cookie = request.POST.get('cookie', None)
        captcha = request.POST.get('captcha', None)
        rno = request.POST.get('rno', None)
        image = request.POST.get('image', None)
        if username and password and cookie and captcha and rno:
            sysuer = Sysuer(username=username, password=password, cookie=cookie)
            try:
                sysuer.login(captcha, rno)
                success = True
            except:
                success = False
            if success:
                nextPage = request.POST.get('next', '/')
                saveImageAsCorrectName(image, captcha)
                request.session['cookie'] = cookie
                user, created = User.objects.get_or_create(username=username)
                user.set_password(password)
                user.save()
                if created:
                    getGrades(user, sysuer)
                user = auth.authenticate(username=username, password=password)
                auth.login(request, user)
                return redirect(nextPage)
    user = Sysuer()
    user.getLoginData()
    return render(request, 'base/login.html', {
        'cookie': user.cookie,
        'image': user.image,
        'rno': user.rno,
        'next': nextPage,
    })

def saveImageAsCorrectName(path, name):
    os.rename(os.path.join('media', 'captcha', path.split('/')[1]),
        os.path.join('media', 'captcha', str(name) + '.jpg'))

@require_GET
def logout(request):
    auth.logout(request)
    return redirect('/login/')

src/base/templates/base/base.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>{% block title %}{% endblock %}</title>
    <!-- <link rel="shortcut icon" type="image/icon" href="/base/static/images/favo.ico" /> -->
    {% load staticfiles %}
    <!-- Loading Logo -->
    <link rel="shortcut icon" href="{% static 'base/images/logo.ico' %}">
    <!-- Loading Bootstrap -->
    <link href="{% static 'base/css/vendor/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Loading Flat UI -->
    <link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'base/css/demo.css' %}" rel="stylesheet" type="text/css">
    <!-- Loading base.css -->
    <link href="{% static 'base/css/base.css' %}" rel="stylesheet" type="text/css">
    {% block import %}{% endblock %}
</head>

<body>
<header>{% block header %}{% endblock %}</header>


{% block nav %}
<nav class="navbar navbar-inverse navbar-static-top" role="navigation" id="base-nav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-5">
            <span class="sr-only">Toggle navigation</span>
        </button>
        <a class="navbar-brand" href="{% url 'base:index' %}">课霸</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-5">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'lesson:lessons_list' %}">所有课程</a></li>
            <li><a href="{% url 'exchange:all_exchanges' %}">换课信息</a></li>
            <li><a href="#">About Us</a></li>
        </ul>
        <form class="navbar-form navbar-left" action="{% url 'lesson:lessons_list' %}" role="search">
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" id="navbarInput-01" type="search" placeholder="Search" name="p">
                    <span class="input-group-btn">
                        <button type="submit" class="btn"><span class="fui-search"></span></button>
                    </span>
                </div>
            </div>
        </form>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'grade:grade' %}">我的成绩</a></li>
                    <li><a href="{% url 'exchange:my_exchanges' %}">换课记录</a></li>
                    <li><a href="{% url 'lesson:select_result' %}">选课结果</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'base:logout' %}"><span class="fui-power"></span> 注销</a></li>
                </ul>
            </li>
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>
{% endblock nav %}

<main>{% block main %}{% endblock %}</main>

<footer>{% block footer %}{% endblock %}</footer>

<!-- jQuery (necessary for Flat UI's JavaScript plugins) -->
<script src="{% static 'base/js/vendor/jquery.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'base/js/vendor/video.js' %}"></script>
<script src="{% static 'base/js/flat-ui.min.js' %}"></script>
{% block js %}
<script src="{% static 'base/js/application.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{% endblock %}
</body>
</html>

src/base/templates/base/index.html
{% extends "base/base.html" %}

{% block title %}首页{% endblock %}

{% block import %}
{% load staticfiles %}
<link href="{% static 'base/css/index.css' %}" rel="stylesheet" type="text/css">
{% endblock import %}

{% block main %}
<div class="index-image">
    <img src="{% static 'base/images/background2.png' %}" alt="中山大学">
</div>
<div class="index-icon row">
    <div class="function-icon col-md-4">
        <a href="{% url 'lesson:lessons_list' %}">
            <img src="{% static 'base/images/icon-lesson.png' %}">
            <p>课程统计</p>
        </a>
    </div>
    <div class="function-icon col-md-4">
        <a href="{% url 'exchange:all_exchanges' %}">
            <img src="{% static 'base/images/icon-exchange.png' %}">
            <p>交换课程</p>
        </a>
    </div>
    <div class="function-icon col-md-4">
        <a href="{% url 'grade:grade' %}">
            <img src="{% static 'base/images/icon-personal.png' %}">
            <p>个人成绩</p>
        </a>
    </div>
</div>
{% endblock main %}

src/base/templates/base/login.html
{% extends 'base/base.html' %}

{% block title %}登录{% endblock %}

{% block import %}
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'login/css/login.css' %}">
{% endblock import %}

{% block nav %}{% endblock nav %}

{% block main %}
<div class="login">
    <div class="login-screen">
        <div class="login-icon">
            <img src="{% static 'base/images/login.png' %}" alt="Welcome to CURRICULUM" />
            <h4>Welcome to <small>CURRICULUM</small></h4>
        </div>

        <div class="login-form">
            <div class="form-group">
                <form action="{% url 'base:login' %}" method="post">
                {% csrf_token %}
                    <div class="control-group">
                        <input type="text" class="form-control login-field" value="" placeholder="请输入教务系统账号" id="login-name" name="username" />
                        <label class="login-field-icon fui-user" for="login-name"></label>
                    </div>
                    <div class="control-group">
                        <input type="password" class="form-control login-field" value="" placeholder="请输入密码" id="login-pass" name="password" />
                        <label class="login-field-icon fui-lock" for="login-pass"></label>
                    </div>
                    <div class="control-group">
                        <input type="text" class="form-control login-field" value="" placeholder="请输入验证码" id="login-pass" name="captcha" />
                        <label class="login-field-icon" for="login-pass"><img id="captcha" src="{% url 'media' image %}"/></label>
                    </div>
                    <input type="hidden" id="login-cookie" name="cookie" value="{{ cookie }}">
                    <input type="hidden" id="login-rno" name="rno" value="{{ rno }}">
                    <input type="hidden" name="next" value="{{ next }}">
                    <input type="hidden" name="image" value="{{ image }}">
                    <button class="btn btn-primary confirm-button">登录</button
                </form>
            </div>
            <p class="login-link">第一次登录的话等待时间会较长</a>
    </div>
</div>
  </div>
{% endblock main%}

{% block js %}
<script src="{% static 'login/js/login.js' %}"></script>
{% endblock %}

src/base/templates/base/test.html
{{ data }}