src/SysuLesson/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import settings

urlpatterns = [
    url(r'', include('base.urls', namespace='base')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^exchange/', include('exchange.urls', namespace='exchange')),
    url(r'^grade/', include('grade.urls', namespace='grade')),
    url(r'^lesson/', include('lesson.urls', namespace='lesson')),
    url(r'^meterial/', include('meterial.urls', namespace='meterial')),
    url(r'^school/', include('school.urls', namespace='school')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }, name='media'),
]

src/base/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^test/$', views.test, name='test'),
]

src/comment/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^create/$', views.create_comment, name='create'),
]

src/lesson/urls.py
from django.conf.urls import patterns, url


from lesson import views

urlpatterns = patterns('',
    url(r'^$', views.lessons_list, name='lessons_list'),
    url(r'^(?P<lesson_id>\d+)/$', views.lesson_detail, name='lesson_detail'),
    url(r'^home/$', views.select_result, name='select_result'),
)

src/lesson/models.py
# -*- coding: utf-8 -*-
from django.db import models

from school.models import School
# Create your models here.

class Lesson(models.Model):
    school = models.ForeignKey(School)
    lessonId = models.CharField(max_length = 32)
    title = models.CharField(max_length = 128)
    description = models.TextField(null = True, blank = True)
    classHour = models.CharField(max_length = 16)
    credit = models.CharField(max_length = 8)
    campus = models.CharField(max_length = 16, choices = (
        ('4', u'东校区'),
        ('2', u'北校区'),
        ('3', u'南校区'),
        ('1', u'珠海校区')
    ), null = True, blank = True)
    teacher = models.CharField(max_length=128, null = True, blank = True) #老外的名字太长了
    teachType = models.CharField(max_length = 4, choices = (
        ('01', u'主修'),
        ('02', u'辅修'),  #unkonw
        # todo 
    ))
    type = models.CharField(max_length = 4, choices = (
        ('10', u'公必'),
        ('11', u'专必'),
        ('30', u'公选'),
        ('21', u'专选'),
    ))
    evaluationValue = models.IntegerField(default = 0)
    evaluationCount = models.IntegerField(default = 0)
    gradeNumber = models.IntegerField(default = 0)

    def add_grade_number(self):
        self.gradeNumber += 1

    def get_evaluation(self):
        try:
            return self.evaluationValue/self.evaluationCount
        except:
            return 0

    def __unicode__(self):
        return self.title

    def add_evaluation(self, value):
        self.evaluationValue += value
        self.evaluationCount += 1

    class Meta:
        ordering = ['-evaluationCount', '-gradeNumber', 'title']
        verbose_name = 'Lesson'
        verbose_name_plural = 'Lessons'
        unique_together = ('lessonId', 'teacher', )

src/lesson/views.py
from django.shortcuts import render
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth.decorators import login_required

from django.db.models import Q

from .models import Lesson
from comment.models import Comment
from meterial.models import Meterial
from api.myLesson import MyLesson
from api.sysu import Sysuer
from api.parser import parseResultOfCourseSelection, parseScore

# Create your views here.
@require_GET
@login_required
def lessons_list(request):
    search = request.GET.get('p', None)
    if search is not None:
        all_lessons = Lesson.objects.filter(Q(title__contains=search) | Q(teacher__contains=search))
    else:
        all_lessons = Lesson.objects.all()
    paginator = Paginator(all_lessons, 25)

    page = request.GET.get('page')
    try:
        lessons = paginator.page(page)
    except PageNotAnInteger:
        lessons = paginator.page(1)
    except EmptyPage:
        lessons = paginator.page(paginator.num_pages)

    return render(request, 'lesson/lessons_list.html', {
        'lessons': lessons,
        'search': search,
        })


@login_required
@require_GET
def lesson_detail(request, lesson_id):
    try:
        lesson = Lesson.objects.get(pk=lesson_id)
    except Lesson.DoesNotExist:
        raise Http404('Lesson does not exist...')
    user = request.user
    comments = Comment.objects.filter(user=user).filter(lesson=lesson)
    meterials = Meterial.objects.filter(lesson=lesson)
    return render(request, 'lesson/lesson_detail.html', {
        'lesson': lesson,
        'comments': comments,
        'meterials': meterials,
    })

@login_required
@require_GET
def select_result(request):
    user = Sysuer(username=request.user.username,
        cookie=request.session['cookie'])
    lessons = parseResultOfCourseSelection(user)
    for x in lessons:
        try:
            lesson = Lesson.objects.get(lessonId=x['kch'], teacher=x['xm'])
            x.set('id', lesson.id)
        except:
            pass
    return render(request, 'lesson/select_result.html', {
        'lessons': lessons,
    })

src/lesson/templates/lesson/lesson_detail.html
{% extends 'base/base.html' %}

{% block import %}
{% load staticfiles %}

<link href="{% static 'lesson/css/lesson.css' %}" rel="stylesheet">

<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
<!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
{% endblock import %}

{% block js %}
<script src="{% static 'lesson/js/lesson.js' %}" type="text/javascript"></script>
<script src="{% static 'lesson/js/Chart.js' %}" type="text/javascript"></script>
{% endblock %}


{% block main %}
<div class="container">
    <h2>{{ lesson.title }}</h2>
</div>
<!-- /.container -->

<div class="container well center-block">
    <div class="row"><!-- Lesson info -->
      <dl class="dl-horizontal col-sm-6">
          <dt>描述</dt>
          <dd>{{ lesson.description|default:'None' }}</dd>
      </dl>
      <dl class="dl-horizontal col-sm-6">
          <dt>课时</dt>
          <dd>{{ lesson.classHour }}</dd>
      </dl>
      <dl class="dl-horizontal col-sm-6">
          <dt>学分</dt>
          <dd>{{ lesson.credit }}</dd>
      </dl>
      <dl class="dl-horizontal col-sm-6">
          <dt>教师</dt>
          <dd>{{ lesson.teacher|truncatechars:20 }}</dd>
      </dl>
      <dl class="dl-horizontal col-sm-6">
          <dt>校区</dt>
          <dd>{{ lesson.get_campus_display }}</dd>
      </dl>
      <dl class="dl-horizontal col-sm-6">
          <dt>培养类别</dt>
          <dd>{{ lesson.get_teachType_display }}</dd>
      </dl>
      <dl class="dl-horizontal col-sm-6">
          <dt>课程类型</dt>
          <dd>{{ lesson.get_type_display }}</dd>
      </dl>
    </div>
    <div class="row"><!-- Chart area -->
      <canvas class="col-sm-5" id="chart-average"></canvas>
      <div class="col-sm-2"></div>
      <canvas class="col-sm-5" id="chart-distribution"></canvas>
    </div>
</div>

<div id="belowPart" class="row container">
    <div class="col-md-8 ">
        <div class="h4 block-heading">评论</div>
        <div ><!--Comments area -->
            {% if comments %}
            {% for comment in comments %}
            <div class="panel panel-primary">
                <div class="panel-body text-left">{{ comment.content }}</div>
                <div class="panel-footer text-left">
                    <span>{{ comment.name }}</span>
                    <span>{{ comment.time }}</span>
                    <button type="button" class="reply-btn btn btn-primary" data-toggle="modal" data-target="#inputModal">回复</button>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>暂时还没有评论哦。</p>
            {% endif %}
        </div><!--Comments area end-->
        <div><!-- New comment -->
            <button type="button" class="reply-btn btn btn-primary" data-toggle="modal" data-target="#inputModal">回复</button>
        </div><!-- New comment end -->
    </div>
    <div class="col-md-4 ">
        <div class="h4 block-heading">资源</div>
        <div class="well">
            {% if meterials %}
            <ul class="list-unstyled text-center">
                {% for meterial in meterials %}
                <li><a href="{% url 'media' meterial.file %}" download class="col-md-6  col-sm-4 col-xs-12">{{ meterial.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>快来分享您的课程资源啦！</p>
            {% endif %}
            <iframe name="file-upload-iframe" id="file-upload-iframe"></iframe>
            <form class="text-center" method="post" enctype="multipart/form-data" action="{% url 'meterial:create' %}">
            {% csrf_token %}
                <input type="file" id="fileUpload" class="form-control" name="file">
                <input type="text" name="title" class="form-control" placeholder="标题">
                <input type="hidden" name="lesson" value="{{ lesson.id }}">
                <p></p>
                <button type="submit" class="btn btn-success">发布</button>
                </input>
            </form>
            </div>
    </div>
</div>

<div><!-- Modal-->
  <div class="modal fade" id="inputModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <iframe name="comment-iframe" id="comment-iframe"></iframe>
    <form class="modal-dialog" role="document" method="post" action="{% url 'comment:create' %}">
    {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">发布评论</h4>
        </div>
        <div class="modal-body">
          <textarea id="commentContent" row="5" class="commentArea form-control" name="content"></textarea>
        </div>
        <div class="modal-footer">
          <input type="hidden" name="lesson" value="{{ lesson.id }}">
          <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
          <button class="btn btn-success">发布</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script type="text/javascript">
    lessonId = {{ lesson.lessonId }};
</script> <!-- Use an ugly way to restore leesonId to be use in js. -->

<script>
    var randomScalingFactor = function(){ return Math.round(Math.random()*100)}; // Generate random data here, for debug only.
    lineChartData = {
      labels : ["2009", "2010", "2011", "2012", "2013", "2014", "2015"],
      datasets : [
        {
          label: "History average grades",
          fillColor: "rgba(151,187,205,0.2)",
          strokeColor: "rgba(151,187,205,1)",
          pointColor: "rgba(151,187,205,1)",
          pointStrokeColor: "#fff",
          pointHighlightFill: "#fff",
          pointHighlightStroke: "rgba(151,187,205,1)",
          data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]  // History data here.
        },
      ]
    };

    pieData = [
        {
          value: 300,
          color:"#F7464A",
          highlight: "#FF5A5E",
          label: "90~100"
        },
        {
          value: 50,
          color: "#46BFBD",
          highlight: "#5AD3D1",
          label: "80~90"
        },
        {
          value: 100,
          color: "#FDB45C",
          highlight: "#FFC870",
          label: "70~80"
        },
        {
          value: 40,
          color: "#949FB1",
          highlight: "#A8B3C5",
          label: "60~70"
        },
        {
          value: 120,
          color: "#4D5360",
          highlight: "#616774",
          label: "0~60"
        }
      ];
  </script>

{% endblock main %}

src/lesson/templates/lesson/lessons_list.html
{% extends "base/base.html" %}

{% block import %}
{% load staticfiles %}
<link href="{% static 'lesson/css/lessons_list.css' %}" rel="stylesheet" type="text/css">
{% endblock import %}

{% block main %}
<div class="panel panel-primary lesson-panel">
    <div class="panel-heading">
        <h6>课程查询</h6>
    </div>
    <div class="panel-body">
        {% if lessons %}
        <div class="table">
            <table>
                <tr>
                    <th>课程名称</th>
                    <th>任课老师</th>
                    <th>课程类别</th>
                    <th>培养类别</th>
                    <th>所属校区</th>
                    <th>所属学院</th>
                    <th>推荐程度</th>
                </tr>
                {% for lesson in lessons %}
               <tr>
                    <td><a href="{% url 'lesson:lesson_detail' lesson.id %}">{{ lesson.title }}</a></td>
                    <td>{{ lesson.teacher|truncatechars:18|default:'无教师信息' }}</td>
                    <td>{{ lesson.get_type_display }}</td>
                    <td>{{ lesson.get_teachType_display }}</td>
                    <td>{{ lesson.get_campus_display|default:'无校区信息' }}</td>
                    <td>{{ lesson.school.name }}</td>
                    <td>{{ lesson.get_evaluation }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% else %}
        <p>System Error: There are no lessons in databases.</p>
        {% endif %}
        <div class="pagination">
            <span class="step-links">
                {% if lessons.has_previous %}
                    {% if search %}
                    <a href="?p={{ search }}&page={{ lessons.previous_page_number }}">previous</a>
                    {% else %}
                    <a href="?page={{ lessons.previous_page_number }}">previous</a>
                    {% endif %}
                {% endif %}

                <span class="current">
                    Page {{ lessons.number }} of {{ lessons.paginator.num_pages }}.
                </span>

                {% if lessons.has_next %}
                    {% if search %}
                    <a href="?p={{ search }}&page={{ lessons.next_page_number }}">next</a>
                    {% else %}
                    <a href="?page={{ lessons.next_page_number }}">next</a>
                    {% endif %}
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock main %}

src/lesson/templates/lesson/select_result.html
{% extends "base/base.html" %}

{% block title %}选课结果{% endblock %}

{% block import %}
{% load staticfiles %}
<link href="{% static 'lesson/css/select_result.css' %}" rel="stylesheet" type="text/css">
{% endblock import %}

{% block main %}

    <div class="container">
        <h2>选课结果</h2>
    </div>
    <!-- /.container -->

    <div class="container center-block select-block">
    <table class="well table">
        <tr class="row">
            <th class="col-md-3">名称</th><!-- Course name-->
            <th class="col-md-2">教师</th><!-- Teacher name-->
            <th class="col-md-1" class="col-md-3">学分</th><!-- Credit -->
            <th class="col-md-6">时间地点</th><!-- Location and time-->
        </tr>

      {% for lesson in lessons %}
        <tr class="row">
            {% if lesson.id %}
            <td class="col-md-3"><a href="{% url 'lesson:lesson_detail' lesson.id %}">{{lesson.kcmc}}</a></td>
            {% else %}
            <td class="col-md-3">{{lesson.kcmc}}</td>
            {% endif %}
            <td class="col-md-2">{{lesson.xm}}</td>
            <td class="col-md-1">{{lesson.xf}}</td>
            <td class="col-md-6">{{lesson.sksjdd}}</td>
        </tr>
      {% endfor %}

    </table>
    </div>
{% endblock main %}